name: rl-rec-gpu
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - scikit-learn=1.4.2
  - pip
  - pip:
      - gymnasium==0.29.1
      - stable-baselines3==2.3.0
      - shimmy==1.3.0
